### ISSUE TITLE
Please credit "Limor Fried"  / Adafruit on your code that you used from Limor / Adafruit...

### ISSUE THREAD

**Issue by ptorrone** [ananevilya/Arduino-ST7789-Library#10]
Your code says "Written by Ananev Ilya"

However - Please credit "Limor Fried"  / Adafruit on your code that you used from Limor / Adafruit... as it is Limor's code from us (Adafruit).

Thanks.

**Comment by ananevilya** [comment]
Oh, you are right. I made a bad thing. I'll change it ASAP.

**Comment by ananevilya** [comment]
Done.
