### ISSUE TITLE
library stopped working

### ISSUE THREAD

**Issue by macbattlecode** [ananevilya/Arduino-ST7789-Library#11]
Hi,
thank you for the library!

But unfortunately it stopped working after an update of either the board library (Adafruit itsybitsy m4) or the Adafruit GFX library. 

I used hardware SPI without chip select before and it worked fine but for some reason it stopped working and I cannot find the Adafruit GFX library version that worked anymore.

At the moment I try all the library versions (except the itsybitsy ones) but I cannot get it to work again.

The screen stay black and the serial port of the module does not open anymore.

Does anybody has a similar issue?

Have a nice day!

**Comment by ananevilya** [comment]
Hi, thanks for your report.
I'll try to check new version of Adafruit GFX library in 4 days.

**Comment by ananevilya** [comment]
Sorry for late answer. I forgot that I left my display in another city.
So, today a checked this library with updated Adafruit-GFX-Library and everything worked fine.
