### ISSUE TITLE
1.3 pins

### ISSUE THREAD

**Issue by firatkaya7** [ananevilya/Arduino-ST7789-Library#4]
Hello i have this product:
 https://s.click.aliexpress.com/e/taFJRNe
I how to make wire scheme?
Example:
SCL => SCLK
SDA => MOSI...

**Comment by firatkaya7** [comment]
We can how to change back light value?

**Comment by ananevilya** [comment]
No, no way.

пт, 4 янв. 2019 г., 11:00 firatkaya7 notifications@github.com:
